#!/usr/bin/env bash

#stack exec bmm-simulate -- -n 100000 -s 1 --gamma-shape 0.3 --gamma-ncat 4
#stack exec bmm-simulate -- -n 100000 -s 1 -m HKY[7.0][0.5,0.2,0.2,0.1] --gamma-shape 0.3 --gamma-ncat 4
#stack exec bmm-simulate -- -n 100000 -s 1 -m JC --gamma-shape 0.3 --gamma-ncat 4
#stack exec bmm-simulate -- -n 100000 -s 1 -m GTR[1.2,1.3,1.4,1.5,1.6][0.3,0.2,0.1,0.4] --gamma-shape 0.3 --gamma-ncat 4
#stack exec bmm-simulate -- -n 50000 -s 1 --heterozygosity 0.01 --gamma-shape 1.0 --gamma-ncat 4
stack exec bmm-simulate -- -n 100000 -s 1 --heterozygosity 0.01 --gamma-shape 1.0 --gamma-ncat 4 --tree-type Yule --tree-yule-rate 100 --tree-height 0.01

# Or without seed.
# stack exec bmm-simulate -- -n 100000
